files:
  - source: /localization/en/*.xlf
    translation: /localization/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /localization/*/ReadMe-en.xlf
    translation: /localization/%original_path%/ReadMe-%two_letters_code%.xlf
    update_option: update_as_unapproved
